// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: .api/v1/grouping.proto

package grouping_v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// GroupingServiceClient is the client API for GroupingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupingServiceClient interface {
}

type groupingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupingServiceClient(cc grpc.ClientConnInterface) GroupingServiceClient {
	return &groupingServiceClient{cc}
}

// GroupingServiceServer is the server API for GroupingService service.
// All implementations must embed UnimplementedGroupingServiceServer
// for forward compatibility.
type GroupingServiceServer interface {
	mustEmbedUnimplementedGroupingServiceServer()
}

// UnimplementedGroupingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroupingServiceServer struct{}

func (UnimplementedGroupingServiceServer) mustEmbedUnimplementedGroupingServiceServer() {}
func (UnimplementedGroupingServiceServer) testEmbeddedByValue()                         {}

// UnsafeGroupingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupingServiceServer will
// result in compilation errors.
type UnsafeGroupingServiceServer interface {
	mustEmbedUnimplementedGroupingServiceServer()
}

func RegisterGroupingServiceServer(s grpc.ServiceRegistrar, srv GroupingServiceServer) {
	// If the following call pancis, it indicates UnimplementedGroupingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GroupingService_ServiceDesc, srv)
}

// GroupingService_ServiceDesc is the grpc.ServiceDesc for GroupingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lp.data.v1.grouping.GroupingService",
	HandlerType: (*GroupingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    ".api/v1/grouping.proto",
}
