// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: .api/v1/grouping.proto

package grouping_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Grouping - A data grouping container representing a typed set of items.
type Grouping struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this grouping (UUID v4).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Type classification for this grouping.
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grouping) Reset() {
	*x = Grouping{}
	mi := &file___api_v1_grouping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grouping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grouping) ProtoMessage() {}

func (x *Grouping) ProtoReflect() protoreflect.Message {
	mi := &file___api_v1_grouping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grouping.ProtoReflect.Descriptor instead.
func (*Grouping) Descriptor() ([]byte, []int) {
	return file___api_v1_grouping_proto_rawDescGZIP(), []int{0}
}

func (x *Grouping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Grouping) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File___api_v1_grouping_proto protoreflect.FileDescriptor

const file___api_v1_grouping_proto_rawDesc = "" +
	"\n" +
	"\x16.api/v1/grouping.proto\x12\x13lp.data.v1.grouping\".\n" +
	"\bGrouping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type2\x11\n" +
	"\x0fGroupingServiceB\"Z cmd/data/v1/grouping;grouping_v1b\x06proto3"

var (
	file___api_v1_grouping_proto_rawDescOnce sync.Once
	file___api_v1_grouping_proto_rawDescData []byte
)

func file___api_v1_grouping_proto_rawDescGZIP() []byte {
	file___api_v1_grouping_proto_rawDescOnce.Do(func() {
		file___api_v1_grouping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file___api_v1_grouping_proto_rawDesc), len(file___api_v1_grouping_proto_rawDesc)))
	})
	return file___api_v1_grouping_proto_rawDescData
}

var file___api_v1_grouping_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file___api_v1_grouping_proto_goTypes = []any{
	(*Grouping)(nil), // 0: lp.data.v1.grouping.Grouping
}
var file___api_v1_grouping_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file___api_v1_grouping_proto_init() }
func file___api_v1_grouping_proto_init() {
	if File___api_v1_grouping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file___api_v1_grouping_proto_rawDesc), len(file___api_v1_grouping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file___api_v1_grouping_proto_goTypes,
		DependencyIndexes: file___api_v1_grouping_proto_depIdxs,
		MessageInfos:      file___api_v1_grouping_proto_msgTypes,
	}.Build()
	File___api_v1_grouping_proto = out.File
	file___api_v1_grouping_proto_goTypes = nil
	file___api_v1_grouping_proto_depIdxs = nil
}
