api_addr: ":8080"          # REST API address (empty disables API)
runners:
  # Seconds before we time out a job which is not finished.
  # Default: 60
  #
  timeout: 60
  # Number of jobs that can run concurrently.
  # Default: 1
  #
  max_concurrent: 1
pipelines:
  directories:
    - /home/schoo077/lp/.example/pipelines
listeners:
  - type: file_watcher
    name: code-watcher
    pipeline: build
    config:
      path: /home/schoo077/lp/.example/pipelines/src
      pattern: "test"